travis:
  secure:
    BINSTAR_TOKEN: GScqRSy5mw+/aFyBM92jvAe8xwibH1xl8b0i/+Da4Q67d8R6N+hOmF5ULMht9jfCjI+o5hpxPEu5fdv4FLH9hlVjRoIK3Ura4SL3aeQThuxoJw/dcYhADpk+hY/0LtXiOLPmApmHQ3n+mG9J3HR6LU8kN45hOu0IZtkm2D13td/88Qd6L3ju+WCAEGwytocw8Fww31w38AZbR8TeTrc1yAoz6T+hi1fvNphi7wvctU2R2GJjGOD3Wbu2t02LTb5p0K5hIQTpwKkZv0fMh7YDQiMCJoSwA5jFnCwzrd0xelpvnaGW1sZsjv8GngTvYHsoZ58MOkIM+DfcOk9dLUsV1LgM5MSN2cdDjVxpUJdlw2b9BwUAW8m0r6a24qIw6rqpixf6FO+RM8GAm09yklONwdHtTmtNB0kpupU88RS/+B4NdwItVDMFltAYnIRqZwMy09l55l/YeLaZsveNrXq0kvqYbGZz5hpvYm3q1WRp/cPU/5bj36o6rBlniONakUWwTxzhzqB9/2KRKSm0+U/d8rLi5uVb9jP1gpyk9ZJPKzsKVbROP1iyZIx753N1/z6iO9JdDwgq1WeVM1bWg8l4dhhCZo0U4/vP7DdnDlQ4uerxg5d+W9VaEuw8rN13BrhzLtbYPwYxO279LYOsWSjW9fTXttxBk618kmYAIUZn57g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
