travis:
  secure:
    BINSTAR_TOKEN: HN3yv2yisWLDP5Vi1fpQydPp1OgJna10kP0M38pa+sm5d3XZItq1MKGcF3IJJ3TzU/X3Mf5Low1DGHOR0c7PXHGy9NNW+L/ECISG1b7ngX+4OSkMsGxCGPpJI09slmpwBLa8l6u2OXben/kg7OLp1c4jTozmLbanPkRtmJa7GkYGu6zf9fp8Q7ddKga7X/Gbt1fqlxsO/j/y4kgwrHHBJjwWPrfniHabCKO9APO1eKzt51pJB/Di+E2afji+abLOd9Kfoq0rTJfiET9e81acL8FyfH5fPubtQZwVAbGvctBJKxNDWJCiC0E0cD+8WZ7K/TaSrhepKn44EhqWxJyFUh3Z869FC3jgfVsrJdYV1ai32FgqI9gbLcoGom+FNky4zRSqcz8yYVQlYP6SWe3lrQ5L7yrX7SlkFp6VZDp2q/5ps00U8JGccm2yEp83XwdLLXOvPoxo8OXkYVRPgfSeQdQ1eYbwgQSDCh1NEDXrIsKGpXRbjewM9OeaxNc73Zg+2/b8kimD69wEqYXQY6bSVJvVSs4v16vbvNbGk0jaYe+f9DsEJQ67OnNikNwiPMM+ryW+1YrVc/GMuHJ14b4O6t5EP8kEIxqGG55/RBXo917aYBo1WqWN1M568wGGHHvUVZ/liq/QMLdug+RlKiuDQHrWuGFOmACozIaHBIS7F7U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
